// ---------------------------------------------------------------------------------------------
// STRONGLY-TYPED IDENTIFIERS
// ---------------------------------------------------------------------------------------------
// Every identifier in the system lives here, grouped in one file because each is four lines of
// pure ceremony and scattering them across five folders would obscure how uniform they are.
// See IStronglyTypedId<TSelf> for why these exist at all.
//
// Each is a `readonly record struct`, so:
//   * no heap allocation - 16 bytes, exactly like the Guid inside;
//   * value equality, GetHashCode and Deconstruct generated by the compiler;
//   * `default(OrderId)` is Guid.Empty, which the guards in aggregate factories reject.
//
// EF Core learns to persist every one of these as a plain `uniqueidentifier` column through a
// single convention (StronglyTypedIdConvention), not a hand-written converter per type.
//
// NOTE ON FILE LAYOUT: this file uses block-scoped namespaces because it declares types in
// several namespaces at once. Every other file in the solution uses file-scoped namespaces
// (enforced by .editorconfig) - the two styles cannot be mixed within one file.
// ---------------------------------------------------------------------------------------------

using LogiFlow.Domain.Common;

namespace LogiFlow.Domain.Catalog
{
    /// <summary>Identifies a <see cref="Product"/>.</summary>
    /// <param name="Value">The underlying GUID.</param>
    public readonly record struct ProductId(Guid Value) : IStronglyTypedId<ProductId>
    {
        /// <inheritdoc />
        public static ProductId From(Guid value) => new(value);

        /// <inheritdoc />
        public static ProductId New() => new(Guid.CreateVersion7());

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }
}

namespace LogiFlow.Domain.Customers
{
    /// <summary>Identifies a <see cref="Customer"/>.</summary>
    /// <param name="Value">The underlying GUID.</param>
    public readonly record struct CustomerId(Guid Value) : IStronglyTypedId<CustomerId>
    {
        /// <inheritdoc />
        public static CustomerId From(Guid value) => new(value);

        /// <inheritdoc />
        public static CustomerId New() => new(Guid.CreateVersion7());

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }
}

namespace LogiFlow.Domain.Orders
{
    /// <summary>Identifies an <see cref="Order"/>.</summary>
    /// <param name="Value">The underlying GUID.</param>
    public readonly record struct OrderId(Guid Value) : IStronglyTypedId<OrderId>
    {
        /// <inheritdoc />
        public static OrderId From(Guid value) => new(value);

        /// <inheritdoc />
        public static OrderId New() => new(Guid.CreateVersion7());

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }

    /// <summary>Identifies an <see cref="OrderLine"/> within its order.</summary>
    /// <param name="Value">The underlying GUID.</param>
    public readonly record struct OrderLineId(Guid Value) : IStronglyTypedId<OrderLineId>
    {
        /// <inheritdoc />
        public static OrderLineId From(Guid value) => new(value);

        /// <inheritdoc />
        public static OrderLineId New() => new(Guid.CreateVersion7());

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }
}

namespace LogiFlow.Domain.Inventory
{
    /// <summary>Identifies a <see cref="Warehouse"/>.</summary>
    /// <param name="Value">The underlying GUID.</param>
    public readonly record struct WarehouseId(Guid Value) : IStronglyTypedId<WarehouseId>
    {
        /// <inheritdoc />
        public static WarehouseId From(Guid value) => new(value);

        /// <inheritdoc />
        public static WarehouseId New() => new(Guid.CreateVersion7());

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }

    /// <summary>Identifies a <see cref="StockItem"/> row.</summary>
    /// <param name="Value">The underlying GUID.</param>
    public readonly record struct StockItemId(Guid Value) : IStronglyTypedId<StockItemId>
    {
        /// <inheritdoc />
        public static StockItemId From(Guid value) => new(value);

        /// <inheritdoc />
        public static StockItemId New() => new(Guid.CreateVersion7());

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }
}

namespace LogiFlow.Domain.Shipping
{
    /// <summary>Identifies a <see cref="Shipment"/>.</summary>
    /// <param name="Value">The underlying GUID.</param>
    public readonly record struct ShipmentId(Guid Value) : IStronglyTypedId<ShipmentId>
    {
        /// <inheritdoc />
        public static ShipmentId From(Guid value) => new(value);

        /// <inheritdoc />
        public static ShipmentId New() => new(Guid.CreateVersion7());

        /// <inheritdoc />
        public override string ToString() => Value.ToString();
    }
}
